openapi: 3.0.0
info:
  title: Gestion de l'authentification
  description: API pour gérer l'authentification des utilisateurs.
  version: 1.0.0

paths:
  /users:
    post:
      summary: Inscription d'un nouvel utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
        '400':
          description: Requête incorrecte
          
  /users/authenticate:
    post:
      summary: Authentification de l'utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Authentification réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
        '401':
          description: Identifiants incorrects
        '400':
          description: Requête incorrecte

  /users/{userId}:
    put:
      summary: Mettre à jour les détails d'un utilisateur
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID de l'utilisateur à mettre à jour
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Utilisateur mis à jour avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
        '400':
          description: Requête incorrecte
        '404':
          description: Utilisateur non trouvé

    delete:
      summary: Supprimer un utilisateur
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID de l'utilisateur à supprimer
      responses:
        '204':
          description: Utilisateur supprimé avec succès
        '404':
          description: Utilisateur non trouvé
